// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4B0OWrT7-p3Ogf9_Q6sCRDOKbEPwyI14',
    appId: '1:650566917364:web:583aa7dde6b456445552a1',
    messagingSenderId: '650566917364',
    projectId: 'amsterdam-bars-bd05a',
    authDomain: 'amsterdam-bars-bd05a.firebaseapp.com',
    storageBucket: 'amsterdam-bars-bd05a.firebasestorage.app',
    measurementId: 'G-H198GMQF5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5D8mGLyDwcVxaPGHcs6jZ8Il1Dhp-QAA',
    appId: '1:650566917364:android:43e26c1057b88d195552a1',
    messagingSenderId: '650566917364',
    projectId: 'amsterdam-bars-bd05a',
    storageBucket: 'amsterdam-bars-bd05a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0mHEv2x3yn7yLHcLmu7Mq1qBaws7rUYE',
    appId: '1:650566917364:ios:4d5b3f0115238c4b5552a1',
    messagingSenderId: '650566917364',
    projectId: 'amsterdam-bars-bd05a',
    storageBucket: 'amsterdam-bars-bd05a.firebasestorage.app',
    iosBundleId: 'com.example.amsterdamBars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0mHEv2x3yn7yLHcLmu7Mq1qBaws7rUYE',
    appId: '1:650566917364:ios:4d5b3f0115238c4b5552a1',
    messagingSenderId: '650566917364',
    projectId: 'amsterdam-bars-bd05a',
    storageBucket: 'amsterdam-bars-bd05a.firebasestorage.app',
    iosBundleId: 'com.example.amsterdamBars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4B0OWrT7-p3Ogf9_Q6sCRDOKbEPwyI14',
    appId: '1:650566917364:web:382cb020cc20ad9d5552a1',
    messagingSenderId: '650566917364',
    projectId: 'amsterdam-bars-bd05a',
    authDomain: 'amsterdam-bars-bd05a.firebaseapp.com',
    storageBucket: 'amsterdam-bars-bd05a.firebasestorage.app',
    measurementId: 'G-H66L53E0PX',
  );

}